### ISSUE TITLE
Add more HTTP Request task full plugin Examples

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/docs#1597]
### Description

Currently, there is not a single example that would be using Content-Type: application/json (only multipart form data) for the [HTTP Request task](https://kestra.io/plugins/core/tasks/http/io.kestra.plugin.core.http.request).

- [ ] add more realistic examples as full plugin examples
- [ ] use multiple content types and multiple authentication methods to show different usage patterns

**Comment by anna-geller** [comment]
part https://github.com/kestra-io/kestra/commit/7411c6d12e8e981ddfb298c7093b1e9c8924048f

**Comment by wrussell1999** [comment]
@shrutimantri A few that we should make examples for:

- [ ] Image type example (e.g. `image/jpeg`) to show how someone could upload an image generated from a previous task (maybe a download from S3 or Google Drive?)
- [ ] `text/csv` example to show how you could upload a CSV file that was generated from a previous task (like download
- [ ] Example authenticating with a JWT
- [ ] Example authenticating an API key in the header

If you can't find real websites that allow you to test making requests, we can use a dummy URL so that people get the idea. The key thing is showing people how they would format these types of examples inside of the task.
